# Generated by Django 3.2.14 on 2023-03-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume', models.IntegerField()),
            ],
            options={
                'db_table': 'financial_data',
            },
        ),
    ]
