# Generated by Django 3.2.14 on 2023-03-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='financialdatamodel',
            unique_together={('symbol', 'date')},
        ),
    ]
